apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "witw.fullname" . }}
  labels:
    {{- include "witw.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "witw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "witw.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "witw.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-migrate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - |
            python manage.py migrate
            python manage.py shell -c 'from cities.models import City; import os; exit(City.objects.count() == 0)' \
              || python manage.py cities --import=all
            python manage.py shell -c 'from backend.models import Team; import os; Team.objects.create(name=(os.getenv("TEAM_NAME") or "Hogflix")) if not Team.objects.exists() else True'
          env:
          - name: DB_HOST
            value: {{ include "witw.fullname" . }}-postgres
          - name: DEBUG
            value: "true"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DB_HOST
            value: {{ include "witw.fullname" . }}-postgres
            {{- if not .Values.ingress.tls }}
          - name: DEBUG
            value: "true"
            {{- end }}
          - name: ALLOWED_HOSTS
            value: "*"
          - name: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
            valueFrom:
              secretKeyRef:
                name: credentials
                key: oauthKey
                optional: false
          - name: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
            valueFrom:
              secretKeyRef:
                name: credentials
                key: oauthSecret
                optional: false
          - name: MAPS_API_KEY
            valueFrom:
              secretKeyRef:
                name: credentials
                key: mapsKey
                optional: false
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_health
              port: http
          readinessProbe:
            httpGet:
              path: /_health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
