{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "witw.fullname" . }}-postgres
  labels:
    {{- include "witw.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "witw.selectorLabelsPostgres" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "witw.selectorLabelsPostgres" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "witw.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: "postgis/postgis:13-master"
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
          - name: db
            mountPath: /var/lib/postgresql/data
          ports:
          - name: postgres
            containerPort: 5432
            protocol: TCP
          env:
          - name: POSTGRES_PASSWORD
            value: whereintheworld
          - name: POSTGRES_USER
            value: whereintheworld
          - name: POSTGRES_DB
            value: whereintheworld
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "witw.fullname" . }}-postgres
  labels:
    {{- include "witw.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    {{- include "witw.selectorLabelsPostgres" . | nindent 4 }}
{{- end }}
