name: Push

on:
  push:
    tags:
      - '*'

jobs:
  push:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u frankh --password-stdin

      # Runs a single command using the runners shell
      - name: Install helm
        run: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Helm Package
        run: helm package charts/witw

      - name: Helm Push
        run: helm push witw-*.tgz oci://registry-1.docker.io/frankh
